---
- hosts: all
  remote_user: linx
  become: yes
  become_method: sudo
  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker
      ## docker file path in your system #####  
  - name: copy the docker file
    copy:
      src: /home/ec2-user/httpd
      dest: /home/ubuntu ######### on remote server destnation path #############
  - name: Build Docker image from Dockerfile
    docker_image:
      name: httpd  ### name of the docker image ####
      path: /home/ubuntu/httpd #### on the remote server where the docker file is stored #####
      state: build

  - name: Running the container
    docker_container:
      name: httpd
      image: httpd
      state: started
      ports:
              - "82:80"
      detach: yes
    register: "contener-id"

